export const LOGIN = "LOGIN";
export const AUTO_LOGIN = "AUTO_LOGIN";
export const LOGOUT = "LOGOUT";

export const CHECK_PHONE_NUMBER = "CHECK_PHONE_NUMBER";
export const CONFIRM_TEXT_MESSAGE = "CONFIRM_TEXT_MESSAGE";
export const REGISTER_ID_CARD = "REGISTER_ID_CARD";
export const REGISTER_VACCINE_PASS = "REGISTER_VACCINE_PASS";
export const REGISTER_PASSWORD = "REGISTER_PASSWORD";
export const CONFIRM_PASSWORD = "CONFIRM_PASSWORD";
export const MODIFY_PASSWORD = "MODIFY_PASSWORD";